### ISSUE TITLE
Please translate documentation to English

### ISSUE THREAD

**Issue by pyhedgehog** [dosgo/ngrok-c#12]
I would be happy to use (and possibly contribute to) this project, but I can't read README, logs and so on...

**Comment by dosgo** [comment]
Welcome you to join the project.I will give you the development file, and make the files easy to read later.

**Comment by dosgo** [comment]
Welcome you to join the project.I will give you the development file, and make the files easy to read later.

**Comment by jim3mar** [comment]
I would be happy to translate from Chinese to English if I have enough time.
