### ISSUE TITLE
编译openssl 出错

### ISSUE THREAD

**Issue by linktest** [dosgo/ngrok-c#23]
buildlib.sh文件如下：

export PATH=$PATH:'/home/linux/1/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin'
export STAGING_DIR="/home/linux/1/staging_dir"
CC=mipsel-openwrt-linux-gcc
CXX=mipsel-openwrt-linux-g++
AR=mipsel-openwrt-linux-ar
RANLIB=mipsel-openwrt-linux-ranlib 
./Configure no-asm shared --prefix=`pwd`/../out/openssl linux-mips32
make clean
make
make install

错误信息：
making all in crypto...
make[1]: Entering directory `/home/linux/openssl-1.0.2h/crypto'
/usr/bin/perl ../util/mkbuildinf.pl "gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -mabi=32 -O3 -Wall -DBN_DIV3W" "linux-mips32" >buildinf.h
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -mabi=32 -O3 -Wall -DBN_DIV3W   -c -o cryptlib.o cryptlib.c
gcc: error: unrecognized argument in option '-mabi=32'
gcc: note: valid arguments to '-mabi=' are: ms sysv
make[1]: *** [cryptlib.o] Error 1
make[1]: Leaving directory`/home/linux/openssl-1.0.2h/crypto'
make: **\* [build_crypto] Error 1
making all in crypto...
make[1]: Entering directory `/home/linux/openssl-1.0.2h/crypto'
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -mabi=32 -O3 -Wall -DBN_DIV3W   -c -o cryptlib.o cryptlib.c
gcc: error: unrecognized argument in option '-mabi=32'
gcc: note: valid arguments to '-mabi=' are: ms sysv
make[1]: *** [cryptlib.o] Error 1
make[1]: Leaving directory`/home/linux/openssl-1.0.2h/crypto'
make: **\* [build_crypto] Error 1

**Comment by dosgo** [comment]
你为啥想编译这些？现在已经不需要编译这些了。。你安装libopenssl.ipk就能运行了。。openwrt已经帮你编译好了。。libopenssl.ipk,运行opkg install libopenssl

**Comment by linktest** [comment]
收到，谢谢，那就不搞了。

**Comment by dosgo** [comment]
编译openssl库确实挺麻烦的。。我只编译过一次。。以后就一直用。
