### ISSUE TITLE
BB版本OP编译后启动报错

### ISSUE THREAD

**Issue by TrueMacho** [dosgo/ngrok-c#24]
按照openwrt傻瓜式教程，可以成功编译出ngrok，但是放到/usr/bin中启动时提示：BusError

**Comment by dosgo** [comment]
提示这么简单？

**Comment by TrueMacho** [comment]
@dosgo 就是这么简洁明了……别的提示一点都没有……我在想是不是我的libopenssl版本太低了？版本是：1.0.1j-1。

**Comment by dosgo** [comment]
不是，你设备特殊吧，我找找原因

**Comment by dosgo** [comment]
什么平台？mips?以前编译过过嘛？

**Comment by TrueMacho** [comment]
@dosgo 好嘞，我也再试试，我的设备信息如下：
> 主机名	OpenWrt
> 主机型号	Qihoo 360 C301
> 固件版本	OpenWrt Barrier Breaker r42406 / LuCI Trunk (0.12+svn-r10522)
> 芯片型号	Atheros AR9344 rev 3
> CPU 频率	560MHz
> 内核版本	3.10.49

**Comment by dosgo** [comment]
BusError之前啥都没打印？

**Comment by TrueMacho** [comment]
@dosgo 是的，没有任何提示，直接就BusError。

**Comment by dosgo** [comment]
在编译脚本 $YH 上加上这行试试 -munaligned-access

**Comment by dosgo** [comment]
这问题没那么容易找原因

**Comment by TrueMacho** [comment]
@dosgo 好嘞，我明天再搞搞试试，不行的话把所有版本来一遍看看都是什么结果……明天反馈哈。3Q~

**Comment by dosgo** [comment]
你明天把
string VER = "1.35-(2016/5/13)";
改成
char VER[30]= "1.36-(2016/5/14)";

  printf("ngrokc v%s \r\n",VER.c_str());改成
  printf("ngrokc v%s \r\n",VER);试试。
分别在main.cpp的68行跟148行。

**Comment by dosgo** [comment]
char VER[28]= "1.36-(2016/5/14)"; 吧

**Comment by TrueMacho** [comment]
![screenshot at 2016-05-15 22 59 04](https://cloud.githubusercontent.com/assets/9412802/15274929/4402cbb8-1af1-11e6-9d11-18757ee44579.png)
还是不可以，上图是在openwrt中的运行提示。 -munaligned-access这个加在$YH后提示：
`mips-openwrt-linux-g++: error: unrecognized command line option '-munaligned-access'`

**Comment by dosgo** [comment]
你修改了main.cpp文件嘛？

**Comment by dosgo** [comment]
实在不行，我看看有没有空，帮你编译个版本，然后你运行测试下，主要是我不知道哪行有问题，也就没发解决。

**Comment by dosgo** [comment]
对了。。你用什么版本的SDK？

**Comment by TrueMacho** [comment]
不好意思，回复晚了~修改了main.cpp文件里面的，改成：
> char VER[28]= "1.36-(2016/5/14)";
> printf("ngrokc v%s \r\n",VER);

但是还是不行，上图就是运行之后的结果，直接就提示Bus error.
麻烦您有空帮我编译一个～多谢大神啦～
SDK版本链接是：[barrier_breaker 14.07 ar71xx](https://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2)

**Comment by dosgo** [comment]
好吧，你能不能把你的设备ssh映射出来，发我邮箱。。然后我测试更方便。

**Comment by TrueMacho** [comment]
@dosgo 可以呀，我晚上回去用路由器下面的电脑用ngrok把路由器的ssh端口映射出去吧，到时候密钥发你邮箱。

**Comment by dosgo** [comment]
你还是先用旧版的ngrokc,映射出来。。别电脑了。。电脑太费电了。。今晚我恐怕没空

**Comment by TrueMacho** [comment]
嗯嗯，好嘞。

**Comment by dosgo** [comment]
解决了？

**Comment by TrueMacho** [comment]
@dosgo 突然就好了……还是按照之前你说的更改的，不过 $YH 没有加 -munaligned-access。如邮件中所示，版本号改成”1.36-(2016/5/14)"。main.cpp文件修改是按照你说的修改的，还是昨天编译的结果，但是今天就能运行了。今天是卸载了之前安装的luci-ngrok，会不会可能跟这个有关？

**Comment by dosgo** [comment]
luci-ngrok这个是啥东西？哪找的？关系不大把

**Comment by TrueMacho** [comment]
@dosgo 之前是[恩山论坛这个帖子](http://www.right.com.cn/forum/thread-184223-1-2.html)上找的……现在帖子更新了。今天就做了3件事：
1.卸载luci-app-ngrokc_git-15.290.16504-8c2fd44-1_all.ipk；
2.重新安装了libstdcpp，现在版本是[libstdcpp_4.8-linaro-1_ar71xx.ipk](https://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/base/libstdcpp_4.8-linaro-1_ar71xx.ipk);
3.复制ngrokc到/usr/bin/里面，chmod +x后运行提示：libmbedtls.so.8找不到，然后做了一个软连接。

**Comment by dosgo** [comment]
啊。。你用傻瓜教程编译的是不需要libmbedtls啊。。是openssl啊，难于理解

**Comment by TrueMacho** [comment]
是呀，但是运行的时候真的是提示libmbedtls缺失～

**Comment by luojunqing** [comment]
@TrueMacho 编译好了的OP Barrier Breaker版本可以发来测试一下吗
luojunqing@hotmail.com
