### ISSUE TITLE
给作者大神提供个asus-merlin固件编译脚本

### ISSUE THREAD

**Issue by tangyl2000** [dosgo/ngrok-c#27]
# !/bin/sh

export PATH=$PATH:'/home/cijliu/work/asuswrt-merlin/release/src-rt-6.x.4708/toolchains/hndtools-arm-linux-2.6.36-uclibc-4.5.3/bin'
export STAGING_DIR="/home/cijliu/work/asuswrt-merlin/release/src-rt-6.x.4708/toolchains"
DIR=build-mips
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/brcm-arm/lib:/usr/local/lib:/usr/lib
mkdir $DIR
rm -rf $DIR/main.o
rm -rf $DIR/cJSON.o
rm -rf $DIR/sendmsg.o
rm -rf $DIR/sslbio.o
rm -rf $DIR/nonblocking.o
rm -rf $DIR/openssldl.o
rm -rf $DIR/ngrokc

CC=arm-brcm-linux-uclibcgnueabi-g++
YH="-Wall -fexceptions -DOPENSSL=1 -DOPENSSLDL=1  -O2"
$CC $YH  -c $1 sendmsg.cpp -o $DIR/sendmsg.o
$CC $YH -c openssldl.cpp -o $DIR/openssldl.o
$CC $YH -c $1 cJSON.c -o $DIR/cJSON.o
$CC $YH -c $1 main.cpp -o $DIR/main.o
$CC $YH -c $1 nonblocking.cpp  -o $DIR/nonblocking.o
$CC $YH -c $1 sslbio.cpp  -o $DIR/sslbio.o
$CC $YH -c $1 ngrok.cpp  -o $DIR/ngrok.o
$CC -s $DIR/main.o $DIR/cJSON.o $DIR/sendmsg.o $DIR/nonblocking.o $DIR/ngrok.o $DIR/sslbio.o  $DIR/openssldl.o  -o $DIR/ngrokc    -ldl

搭建好asus-merlin编译环境之后，设置PATH和STAGING_DIR路径，然后从PATH下找到对应路由器版本的CC编译器名称并在本脚本中修改。

另外，大神您提供的简书教程中，忘了提示编译者修改CC编译器那一步了~~~

非常感谢您的工作，让我能用上最新版本的路由器客户端，哈哈

**Comment by dosgo** [comment]
提交到github吧
