### ISSUE TITLE
各种文件找不到!

### ISSUE THREAD

**Issue by shirakun** [dosgo/ngrok-c#29]
![qq 20160626214614](https://cloud.githubusercontent.com/assets/11274807/16362333/87890cb4-3be7-11e6-9979-6582ed546170.png)
怎办
sdk:OpenWrt-SDK-ramips-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
系统:ubuntu14.04 64位

**Comment by dosgo** [comment]
你看教程了吗？你这很明显没有把openssl copy到你的gcc的include目录。

**Comment by shirakun** [comment]
然而已经复制了

**Comment by dosgo** [comment]
那你知道mipsel-openwrt-linux-uclibc-g++对应的include目录在哪吗？

**Comment by shirakun** [comment]
不知道,按照你的文图教程弄的,失败后又确认了一次

**Comment by dosgo** [comment]
那你复制到哪去了。。

**Comment by shirakun** [comment]
staging_dir/toolchain-mips_xxxxxx/include
这个目录,xxx已经替换为版本了

**Comment by shirakun** [comment]
现在上班的.等会给你找截图

**Comment by dosgo** [comment]
好

**Comment by shirakun** [comment]
OpenWrt-SDK-ramips-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/include
复制到这个目录了

**Comment by dosgo** [comment]
这。。

**Comment by dosgo** [comment]
你看看目录到底有没有文件

**Comment by shirakun** [comment]
我决定全部删掉重新弄,另外openwrtsdk不需要执行升级命令吧
