### ISSUE TITLE
能加入自动重连的功能吗？

### ISSUE THREAD

**Issue by darcyg** [dosgo/ngrok-c#31]
能加入自动重连的功能吗？
在openwrt下，3G网络
先执行ngrokc，tcp模式，本地端口22
用ifdown 3g关闭网络
10s后开启网络ifup 3g
等待拨号成功
拨号成功后，发现远程通道未恢复

最后给你一个openwrt的编译包。
这个包在放在源码编译目录的packages目录下
或sdk编译目录（packages）下都可以用。
只是放在sdk编译目录下时，需要解除依赖（比如openssl）
或将源码包和packages的feeds中的相关工程包（比如依赖的openssl）
拷贝到sdk的packages目录下即可编译
[ngrok-c.tar.gz](https://github.com/dosgo/ngrok-c/files/339273/ngrok-c.tar.gz)

**Comment by dosgo** [comment]
有自动重连，不过，不过大概要一分钟后……，这个时间可以自己设置，要修改源码。

**Comment by darcyg** [comment]
昨天我测试，很久都没有自动重连
远超越1分钟，源码在哪部分？能提示下，我就不一一看代码了

**Comment by dosgo** [comment]
我刚看了下代码。。没有这个，不过每25秒会ping。。一次，，检测到失败，就会重连。。如果没有重连。。可能你是dns解析失败。

**Comment by dosgo** [comment]
我刚又更新了代码，还有，在main.cpp的114行也有检测，60秒。。不过这个依赖，DNS，如果DNS解析失败是不会检查的。

**Comment by darcyg** [comment]
好像我重拨号上去，dns是解析失败了，我用的是4G
我在4G配置里面，强制指定了dns的解析（114.114.114.114,阿里的公开dns）

**Comment by dosgo** [comment]
新版应该不会了，至于指定dns，这种特殊需求，你还是自己改吧

**Comment by dosgo** [comment]
新版应该不会了，至于指定dns，这种特殊需求，你还是自己改吧

**Comment by darcyg** [comment]
新版是指1.37版？我现在编译的就是1.37版
还是有更新的版本在开发中

**Comment by dosgo** [comment]
git pull

**Comment by dosgo** [comment]
1.38

**Comment by dosgo** [comment]
你为啥不配置，系统DNS呢？

**Comment by darcyg** [comment]
我配了系统DNS，好像没效果。我下午再测下
我现在在写openwrt的ngrokc的服务，写的会比较复杂
下面这个是配置
config ngrokc service
		option host demo.demo.com
		option port 1234
		option token ''
config tun
		option name ssh
		# once, keep, none
		option mode 'keep'
		option type tcp
		option ip 127.0.0.1
		option port 22
		option subdomain ''
		option hostname ''
		option rport ''

config tun
		option name http
		# once, keep, none
		option mode 'none'
		option type http
		option ip 127.0.0.1
		option port 80
		option subdomain ''
		option hostname ''
		option rport ''

**Comment by dosgo** [comment]
DNS如果没法解析。。肯定没法连服务器的。。。自己要自定义DNS挺复杂的。。。

**Comment by darcyg** [comment]
恩，我想办法吧，晚点我切个分支，想加上ubus的支持

**Comment by dosgo** [comment]
ubus用来干嘛？

**Comment by darcyg** [comment]
openwrt的一个数据访问接口

**Comment by darcyg** [comment]
我修改了一个版本的。可以在https://github.com/darcyg/ngrok-c看。ubus的查询命令还没加上
调整，增加了线程，增加了mqtt/ubus的条件编译
可以选择通过mqtt来控制或查询（查询为主，查询接口，查询当前通讯会话）
方便我服务器对终端进行统一管理：我用来管理我们的设备（从内网穿透到公网）

想说的是，楼主的代码能用，但结构不好。
c++的编程，混合了不少c的过程型代码。看起来头大，编程习惯需要改进。
楼主要有空，可以考虑重新规整一下框架，再写过，如果用C++我可以帮忙。

我在里面用了修改过的jsonxx做json处理，比cjson方便多了。
个人看法如果项目确定c++，就尽量多用c++的语言风格和思路，不要用c的。
考虑到嵌入式移植，尽量不要用太大的开源库，不用泛型，找些轻量方便的
代码，编译出来体积增加不大。
用cmake编译。未来交叉编译，设置各种条件编译都方便。
晚点我会增加cmake编译的文件

**Comment by dosgo** [comment]
我可以说不会C++，我一直想用纯C，只是找不到想map这么方便的容器。。2.0有什么功能？。。目前，官方2.0的服务器不开源。我想加入UDP打洞功能，打洞检测+转发。

**Comment by darcyg** [comment]
我不想用纯c是，纯c很多东西都必须自己重搞。基本每个完整功能的项目，都得自己备套工具api
一些代码反复写来写去很不爽..

我建议你用c++，慢慢的就知道c++的方便了。
要不你考虑吧ngrok的功能封装一下（c风格也可以）。
其他的重写

**Comment by dosgo** [comment]
有空再说把，那块确实很乱。。又不想重写了。。

**Comment by darcyg** [comment]
更新了，支持ubus了
