### ISSUE TITLE
能不能添加上设置Password功能呢

### ISSUE THREAD

**Issue by ljk4160** [dosgo/ngrok-c#32]
我的服务器有验证Password功能,我看客户端默认是空的,所以只能把服务器的密码设置空才能,能不能添加一个参数,让运行时可以验证Password

**Comment by dosgo** [comment]
已经有这个功能啊，authtoken参数啊，你怎么认证的。

**Comment by ljk4160** [comment]
sendmsg.h的SendAuth方法里有一个Password,你这里设置为空

**Comment by dosgo** [comment]
你为啥就一定要用password这字段呢？官方都没用过，你直接在authtoken参加做手脚，传一个分割的过去。。反正服务器都你修改的。。

**Comment by tuzhis** [comment]
同求，缘故是有个开源的服务端一键安装脚本挺方便的，里面带有用户管理，也是用到了password，如果能搭配起来应该可以出现更多的分享者

**Comment by dosgo** [comment]
好吧，可以加。。

**Comment by dosgo** [comment]
已经加上去了。。。新版

**Comment by tuzhis** [comment]
测试正常，相对go编译出来的占用和稳定性都好了非常多，感谢~

**Comment by gao270615179** [comment]
@tuzhis 请问“缘故是有个开源的服务端一键安装脚本挺方便的”，这个服务端在哪可以找到？

**Comment by ninggu2008** [comment]
@gao270615179 我猜是指koolshare论坛里的。有个clang，还有个 小宝 写的脚本。不必编译啥的，但是参数有userid，password啥的，现在缺少openwrt下客户端和luci界面。现在我还是搞不懂怎么加用户名。。

**Comment by gao270615179** [comment]
@ninggu2008 多谢啊。客户端好像直接用ngrokc就可以了啊。

**Comment by tuzhis** [comment]
@ninggu2008 的确是，脚本的userid对应Password，脚本的authid对应Atoken
