### ISSUE TITLE
ngrok.cc升级了 不知能否增加支持

### ISSUE THREAD

**Issue by disorderman** [dosgo/ngrok-c#33]
ngrok.cc升级后通过clienid的方式连接，不知能否增加支持？

**Comment by dosgo** [comment]
用http://qydev.com/吧。。ngrok.cc老是改。。上次也是擅自修改协议导致，atoken不兼容

**Comment by dosgo** [comment]
已经加上去了，这样配置，ngrok -SER[Shost:ngrokd.ngrok.com,Sport:443,Atoken:xxx,Cid:xxxx] 

参数名Cid，没测试过，你测试反馈下吧。。
