### ISSUE TITLE
X86 openwrt的要怎么编译？

### ISSUE THREAD

**Issue by kysdm** [dosgo/ngrok-c#34]
文章中的脚本应该不适合x86吧？我尝试了好几次都出错

**Comment by dosgo** [comment]
都一样。。

**Comment by kysdm** [comment]
第一次弄编译 不怎么熟悉   我等下再重头编译试试

**Comment by dosgo** [comment]
报啥错啊，贴图啊。。

**Comment by kysdm** [comment]
![image](https://cloud.githubusercontent.com/assets/19630239/18334438/f92f5f7a-75a9-11e6-8564-083ca763600f.png)
编译openssl库，那个CC CXX这些是不是还要修改，大神能不能详细讲下，第一次弄编译见谅

**Comment by dosgo** [comment]
别编译openssl了。。那东西很费神。。

**Comment by kysdm** [comment]
那直接使用ngrok-c-master\openssl文件夹里的吗？

**Comment by dosgo** [comment]
如果你用动态链接就不用，直接跑buildv2.sh

**Comment by kysdm** [comment]
感觉我SDK弄错了,SDK名字是OpenWrt-SDK-15.05-x86-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2，我需要编译的是x86但是我改成CC=i386-openwrt-linux-g++运行后就显示找不到文件，改成i486后应该是编译成功了，但是我去网站上看好像也没找到其它的SDK了
![image](https://cloud.githubusercontent.com/assets/19630239/18335003/624a7298-75ae-11e6-90b1-b2a4891c1442.png)

**Comment by dosgo** [comment]
成功了就好

**Comment by kysdm** [comment]
再一次谢谢大神协助
