### ISSUE TITLE
今天新编译的openwrt，还没有运行上，请问应该哪里找luci用？

### ISSUE THREAD

**Issue by zasl** [dosgo/ngrok-c#35]
命令行实在不在行啊，想找luci用，看到这里有2个但是必须配合1.25，应该怎么解决？

**Comment by dosgo** [comment]
大于1.25都可以

**Comment by dosgo** [comment]
1.1的//

**Comment by zasl** [comment]
这么快的回复啊，我现在把文件已经复制到路由器的bin下，也修改了属性，并且下载了luci 的ipk，直接安装luci的ipk就可以了还是？

**Comment by dosgo** [comment]
直接安装就可以，，。然后luci就会有菜单

**Comment by zasl** [comment]
我去试试看，不需要执行命令行那些的吧，因为这种方法是我头一次遇到

**Comment by zasl** [comment]
界面是有了，没有具体设置，只勾选启用并且保存应用设置了，但是系统进程看不到ngrok的进程，请问如何简单确定已经运行了？

**Comment by dosgo** [comment]
那说明有问题。。你得先。。安装ngrokc的luci界面，再删除/usr/bin/里面的旧版ngrokc,再复制你编译的进去，再加权限。。再设置。。不能乱来

**Comment by zasl** [comment]
我是打算编译到固件里面，复制的话都是最后操作的，应该能按照你的方法过来，我一会再试试看。对了，目录到底是usr/bin还是根目录下的bin呢？我看教程是直接放到根目录下的bin 啊

**Comment by dosgo** [comment]
如果要用luci，必须是usr/bin,

**Comment by dosgo** [comment]
如果要用luci，必须是usr/bin,

**Comment by zasl** [comment]
非常感谢，已经可以用了，谢谢
