### ISSUE TITLE
请问linux服务端能编译吗

### ISSUE THREAD

**Issue by qiurigao** [dosgo/ngrok-c#37]
我编译的原版ngrok服务端，它是证书编译的，没有toke功能，所以ngrokc连不上。
请问有办法解决证书认证问题吗？或者有没有带toke功能的服务端，我想自己架设服务器。
感谢您

**Comment by dosgo** [comment]
官方的默认就没有带token啊。。ngrokc可以连上。。。

**Comment by dosgo** [comment]
官方开源的服务器端，把身份验证这块去掉了。。所以是不用认证的。。

**Comment by qiurigao** [comment]
服务端如何关掉身份验证呢？是带参数运行还是编译前改代码？

**Comment by dosgo** [comment]
验证啥？服务器端没有验证

**Comment by wbp123456** [comment]
请问楼主这个问题解决了吗？
