### ISSUE TITLE
arm编译出错，求帮助

### ISSUE THREAD

**Issue by ivanxxxx** [dosgo/ngrok-c#39]
脚本：
#!/bin/sh
export PATH=$PATH:'/home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin'
export STAGING_DIR="/home/ivan/Lede/1/staging_dir"
DIR=build-arm
mkdir $DIR
rm -rf $DIR/main.o
rm -rf $DIR/cJSON.o
rm -rf $DIR/sendmsg.o
rm -rf $DIR/sslbio.o
rm -rf $DIR/nonblocking.o
rm -rf $DIR/openssldl.o
rm -rf $DIR/ngrokc

CC=arm-openwrt-linux-muslgnueabi-g++
YH="-Wall -fexceptions -DOPENSSL=1 -DOPENSSLDL=1  -O2"
$CC $YH -c $1 sendmsg.cpp -o $DIR/sendmsg.o
$CC $YH -c openssldl.cpp -o $DIR/openssldl.o
$CC $YH -c $1 cJSON.c -o $DIR/cJSON.o
$CC $YH -c $1 main.cpp -o $DIR/main.o
$CC $YH -c $1 nonblocking.cpp  -o $DIR/nonblocking.o
$CC $YH -c $1 sslbio.cpp  -o $DIR/sslbio.o
$CC $YH -c $1 ngrok.cpp  -o $DIR/ngrok.o
$CC -s $DIR/main.o $DIR/cJSON.o $DIR/sendmsg.o $DIR/nonblocking.o $DIR/ngrok.o $DIR/sslbio.o  $DIR/openssldl.o  -o $DIR/ngrokc    -ldl

#buill openssl
#CC=arm-openwrt-linux-gcc
#CXX=arm-openwrt-linux-g++
#AR=arm-openwrt-linux-ar
#RANLIB=arm-openwrt-linux-ranlib 
#./Configure no-asm shared --prefix=`pwd`/../out/openssl linux-mips32
#make
#make install

****************************************************************************************

**# 报错内容：**
ivan@ubuntu:~/Lede/ngrok-c-master$ sudo ./openwrtbuildv2.sh 
mkdir: cannot create directory ‘build-arm’: File exists
/home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: 1: /home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: Syntax error: word unexpected (expecting ")")
/home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: 1: /home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: Syntax error: word unexpected (expecting ")")
/home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: 1: /home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: Syntax error: word unexpected (expecting ")")
/home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: 1: /home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: Syntax error: word unexpected (expecting ")")
/home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: 1: /home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: Syntax error: word unexpected (expecting ")")
/home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: 1: /home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: Syntax error: word unexpected (expecting ")")
/home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: 1: /home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: Syntax error: word unexpected (expecting ")")
/home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: 1: /home/ivan/Lede/1/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/bin/arm-openwrt-linux-muslgnueabi-g++: Syntax error: word unexpected (expecting ")")

是sdk的问题造成吗？ 请问可以帮我编译一个吗？
sdk下载地址：
https://downloads.lede-project.org/snapshots/targets/ipq806x/generic/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64.tar.xz

ivan_choi111@msn.com

**Comment by dosgo** [comment]
你是32位操作系统？

**Comment by ivanxxxx** [comment]
还真是。。。用的32位ubuntu 14.04

要改64？

**Comment by dosgo** [comment]
32位linux会编译出错，原因不明，我也没解决。。

**Comment by ivanxxxx** [comment]
或者能请你帮忙编译一个？

**Comment by dosgo** [comment]
你想多了。。

**Comment by ivanxxxx** [comment]
谢谢你，换64位编译成功了

**Comment by dosgo** [comment]
有时候，自动动手好很多。。。
