### ISSUE TITLE
无法编译polarssl版本

### ISSUE THREAD

**Issue by disorderman** [dosgo/ngrok-c#4]
我自己编译了libpolarssl.a ，但不管是放在工程目录还是建的polarssl目录下都无法编译成功，提示是编译nonblocking.cpp或sslbio时失败，将这些文件中的include<polarssl/xxx>都改为""还是不行，求指导

**Comment by dosgo** [comment]
您修改了config.h配置没有？可能是polarssl版本更新导致的

**Comment by dosgo** [comment]
我当时用的版本好像是这个
#define POLARSSL_VERSION_NUMBER         0x01030A00
#define POLARSSL_VERSION_STRING         "1.3.10"
#define POLARSSL_VERSION_STRING_FULL    "mbed TLS 1.3.10"

**Comment by dosgo** [comment]
https://tls.mbed.org/download-archive 这里有1.3.10版本下载。。

**Comment by disorderman** [comment]
使用你的新代码以后，已经编译成功了，polarssl的Makefile需要修改一下
ngrokc: $(LIBS)
	$(CXX) -s $(LIBS) -o ngrokc -lpthread -lmbedtls -lmbedx509 -lmbedcrypto
就可以了

**Comment by OllivanderMe** [comment]
我在vps运行了一个ngrok server，求教编译newifi(刷了pandorabox)的client具体步骤

**Comment by dosgo** [comment]
@OllivanderMe newifi是神马？

**Comment by OllivanderMe** [comment]
@dosgo 是路由器，联想一个路由器，mt7620a吧，求教如何编译

**Comment by dosgo** [comment]
@OllivanderMe 找对应版本的SDK。。。然后跟其他路由都差不多

**Comment by OllivanderMe** [comment]
@dosgo run openwrtbuild.sh      就直接在路由运行这句编译出这个客户端吗？

**Comment by dosgo** [comment]
基础问题，自己谷歌。。这我帮不了你

**Comment by OllivanderMe** [comment]
@dosgo ok，谢谢了

**Comment by dosgo** [comment]
@OllivanderMe 你完这个，http://see.sl088.com/wiki/Openwrt_SDK_%E7%BC%96%E8%AF%91_Hello_World
然后，打开 openwrtbuild.sh文件看看。。你应该就知道什么意思了。。

**Comment by OllivanderMe** [comment]
@dosgo 好，大神谢谢
