### ISSUE TITLE
openwrt ar71xx 无反应

### ISSUE THREAD

**Issue by sequencer** [dosgo/ngrok-c#40]
`ngrokc -SER[Shost:ngrok.my.domain,Sport:11003] -AddTun[Type:http,Lhost:127.0.0.1,
Lport:2,Sdname:ssh]`
使用之后
只是会显示
```
root@OpenWrt:~# ngrokc -SER[Shost:ngrok.sequencer.xyz,Sport:11003] -AddTun[Type:http,Lhost:127.0.0.1,
Lport:2,Sdname:ssh]
ngrokc v1.40-(2016/10/27)
```
就没有其他的显示了
服务器也没有任何提示
但是如果使用
`ngrokc -SER[Shost:ngrok.my.domain,Sport:4443(一个错误的端口)] -AddTun[Type:http,Lhost:127.0.0.1,
Lport:2,Sdname:ssh]`
则会出现
```
ngrokc v1.40-(2016/10/27)
connect failed...!
link err
```
有没有日志功能让我知道发生了啥...
使用
`nc -v -w 10 -z ngrok.my.domain 11001-11003`
能够提示success

**Comment by dosgo** [comment]
你的服务搭在11003端口？

**Comment by dosgo** [comment]
服务器软件是？

**Comment by sequencer** [comment]
服务器软件用的是最新版的[ngrok官方版](https://github.com/inconshreveable/ngrok)
使用自己的CA编译
运行代码：
`ngrokd -domain "ngrok.my.domain" -httpAddr=":11001" -httpsAddr=":11002" -tunnelAddr=":11003" -log=/var/log/ngrok.log`

**Comment by dosgo** [comment]
你第一次搭服务器吗？

**Comment by sequencer** [comment]
第一次搭ngrok的

**Comment by dosgo** [comment]
ngrok的默认端口是4443吧。。至于这参数是什么意思。。-tunnelAddr=":11003"你还是百度吧

**Comment by dosgo** [comment]
![image](https://cloud.githubusercontent.com/assets/9545458/20388419/a91669d8-acff-11e6-9e98-5bb93407393e.png)然后这里应该是4443

**Comment by sequencer** [comment]
好 谢谢 我去看看文档

**Comment by dosgo** [comment]
http://nullget.sourceforge.net/?q=node/873&lang=en

**Comment by dosgo** [comment]
看这个吧

**Comment by sequencer** [comment]
嗯嗯 好的！谢谢！

**Comment by dosgo** [comment]
![image](https://cloud.githubusercontent.com/assets/9545458/20388465/e5b13436-acff-11e6-99db-2e2f56061f95.png)

**Comment by sequencer** [comment]
我的80和443都被网站占用着
一般就是需要一个TCP的隧道就够了
