### ISSUE TITLE
实测速度比自己编译的ngrok.exe慢

### ISSUE THREAD

**Issue by wdc63** [dosgo/ngrok-c#41]

**Comment by dosgo** [comment]
比go的?

**Comment by dosgo** [comment]
要是能比go快才不正常。。。C要是用网络库，比如event之类的。我觉得勉强打个平手。。功力不到。。写不到，高性能的

**Comment by wdc63** [comment]
谢谢，可是我用owncloud通过ngrok进行资料同步，两者的差距有10倍，go编译的ngrok.exe速度大概800k/s，可是ngrok-c速度只有不到100k/s。服务端用了锐速加速，客户端的win-7 64位。
ngrok-c的好处就是没有内存溢出的问题。go版的ngrok.exe在win平台似乎会把所有的http流量放在内存中，导致占用内存非常大，直到崩溃。

**Comment by wdc63** [comment]
还有个问题想请教一下，ngrok-c是不是一个进程只能同时监听一个http,https和tcp？

**Comment by dosgo** [comment]
对，可以的。

**Comment by dosgo** [comment]
ngrok-c的初衷是设计在路由等设备上映射出，管理页面去的，所以采用的是全平台兼容的select模型，要求的兼容跟稳定，性能没怎么考虑。要达到go的性能不太可能，如果你有兴趣，我给个协议文档你，然后，你自己用网络库重写吧。

**Comment by dosgo** [comment]
可以监听多个tcp，多个http，多个https

**Comment by SouHanaQiao** [comment]
协议文档能给我看看么, 我想用swift实现

**Comment by dosgo** [comment]
@SouHanaQiao 可以。。加群

**Comment by SouHanaQiao** [comment]
@dosgo 群号是?

**Comment by SouHanaQiao** [comment]
@dosgo 申请了

**Comment by JianMingZhuo** [comment]
你好，能给一份协议文档看看吗？
