### ISSUE TITLE
同时多个连接会崩溃，如何差错啊？

### ISSUE THREAD

**Issue by gao270615179** [dosgo/ngrok-c#42]
自己改了一个纯C的（在ubuntu中运行还算正常）移植到嵌入式系统中，同时有超过5、6个连接时就会崩溃，不知道从哪个方面入手查错。
还有没有人有纯C的ngrok啊？

**Comment by dosgo** [comment]
多半是嵌入式内存不够。。

**Comment by gao270615179** [comment]
这个程序在正常情况下会占用多少内存呢？ @dosgo

**Comment by dosgo** [comment]
这个东西有2个线程。。一个主线程，一个数据的。。所以你得看你的线程栈多大。。几个M吧。。要调试也不难。。
