### ISSUE TITLE
断线重连问题

### ISSUE THREAD

**Issue by jiwoon** [dosgo/ngrok-c#43]
当Sdname含有"."时断线重连后会有问题！
测试发现如果Sdname:abc.bcd
第一次运行一切正常，
访问路由器网址为abc.bcd.XXXX.com
当路由器断线后ngrokc重连后会只会返回abc不是返回的abc.bcd
此时访问路由器的网址则变为abc.XXXX.com

**Comment by dosgo** [comment]
什么版本？

**Comment by jiwoon** [comment]
最新的1.4版本

**Comment by dosgo** [comment]
噢，你不能在子域名里面有.,会截取的
