### ISSUE TITLE
亲 怎么添加http验证 给个思路

### ISSUE THREAD

**Issue by wanglinjie168** [dosgo/ngrok-c#44]
没有http验证路由器直接暴露在外网太危险了 原生的客户端是有http验证这个功能的 请问如何实现 给个思路就成

**Comment by dosgo** [comment]
这个简单，在注册http tunnel的时候，有个httpauth你把那参数加上，账号  :密码，就可以了

**Comment by wanglinjie168** [comment]
哈哈  刚摸索出来  谢谢了  还是c的好用 其它的在路由器里不一定好使

**Comment by dosgo** [comment]
那你提交下，合并线上啊

**Comment by wanglinjie168** [comment]
不会玩github呀  而且我是直接改成我的代码了  不是以参数设置的  实在抱歉呀  水平太渣呀
