### ISSUE TITLE
不支持ipv6？

### ISSUE THREAD

**Issue by islercn** [dosgo/ngrok-c#48]
环境为网件4300v1，OpenWrt CC 15.05.1 r49389，用的ipv6线路，一直刷update dns，域名和线路都是通的，添加hosts也不行，换成ipv4的域名就ok了
root@OpenWrt:~# /root/ngrok/ngrokc -SER[Shost:xxx.com,Sport:11111] -AddTun[Type:http,Lhost:127.0.0.1,Lport:80,Sdname:web] -AddTun[Type:tcp,Lhost:127.0.0.1,Lport:23,Rport:11112]
ngrokc v1.41-(2017/01/09) 
update dns
update dns
update dns
update dns
update dns

**Comment by dosgo** [comment]
确实不支持，ipv6没必要端口映射，，，ipv6有提供隧道服务的，可以全端口映射
