### ISSUE TITLE
往syslog里写入太多的日志，有办法消除吗？

### ISSUE THREAD

**Issue by sinowood** [dosgo/ngrok-c#50]
看到很多类似如下的日志，可以设置不写入syslog吗？
user.emerg syslog: {"Type":"Pong","Payload":{}}

**Comment by dosgo** [comment]
第一，这是普通输出，应该不会记录系统日志，可能跟你的运行重定向有关，第二输出你可以关掉，在config.h，关掉重新编译。

**Comment by sinowood** [comment]
好像rc.local里的输出被重定向到syslog了，我加上 > /dev/nul后解决问题，谢谢！
