### ISSUE TITLE
windows 远程连接无法转发

### ISSUE THREAD

**Issue by ryandingf** [dosgo/ngrok-c#57]

**Comment by dosgo** [comment]
可以不要用127.0.0.1

**Comment by ryandingf** [comment]
ngrokc v1.44-(2017/07/25)  openwrt 下编译成功，提示
if ( tempinfo->isconnect == 0 )
					{
					    //检测连接是否可用
						if (check_sock(it1->first)!= 0 )
						{
						    	//关闭远程连接
							if(tempinfo->istype==2){
                                echo("连接本地失败");

提示连接本地失败。用的不是127.0.0.1

**Comment by ryandingf** [comment]
golang-client 正常。

**Comment by dosgo** [comment]
启动命令是啥？

**Comment by ryandingf** [comment]
./ngrokc  -SER[Shost:我的域名,Sport:4443] -AddTun[Type:tcp,Lhost:192.168.1.61,Lport::3389,Rport:60212]

**Comment by dosgo** [comment]
那你检测下192.168.1.61 在本地能telnet吗？

**Comment by ryandingf** [comment]
可以了，命令输入有误。ngrokc1.4 openwrt 下正常。

**Comment by ryandingf** [comment]
谢谢！
