### ISSUE TITLE
openwrt 18.06 luci  错误

### ISSUE THREAD

**Issue by 505575853** [dosgo/ngrok-c#65]
使用的固件 :openwrt-x86-64-combined-squashfs.img 
编译国际的源码:https://github.com/coolsnowwolf/lede
luci版本:src-git luci https://github.com/coolsnowwolf/luci

在使用时出现以下错误:
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: /usr/lib/lua/luci/dispatcher.lua:509: Failed to execute cbi dispatcher target for entry '/admin/services/ngrokc'.
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: The called action terminated with an exception:
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'.
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/tblsection'.
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'ngrokc/overview_value'.
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: A runtime error occured: /usr/lib/lua/luci/model/uci.lua:221: attempt to call method 'get_all' (a nil value)
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: stack traceback:
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: 	[C]: in function 'assert'
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: 	/usr/lib/lua/luci/dispatcher.lua:509: in function 'dispatch'
Sat Oct 27 06:44:58 2018 daemon.err uhttpd[4655]: 	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

**Comment by 505575853** [comment]
![666](https://user-images.githubusercontent.com/31321865/47595859-0d490f80-d9b5-11e8-97bd-e1c3acb640c9.jpg)

**Comment by dosgo** [comment]
luci的问题，我不回答

**Comment by dosgo** [comment]
你们为啥要自己编译，直接安装我这个luci-app-ngrokc_allv1.2.ipk不行吗？

**Comment by RideWindOne** [comment]
> 你们为啥要自己编译，直接安装我这个luci-app-ngrokc_allv1.2.ipk不行吗？

安装这个ipk同样的问题啊。

**Comment by dosgo** [comment]
我没问题哦

**Comment by dosgo** [comment]
又更新了，修复保存不了的问题
