### ISSUE TITLE
fatal error: mbedtls/ssl.h: No such file or directory

### ISSUE THREAD

**Issue by ajmalkhanj** [dosgo/ngrok-c#77]
esp_idf version:v3.1.6-68-ga340a4e-dirty
Operating System: linux
Compiler version:xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 5.2.0

fatal error: mbedtls/ssl.h: No such file or directory
compilation terminated.
CMakeFiles/websockets.dir/build.make:62: recipe for target 'CMakeFiles/websockets.dir/lib/misc/base64-decode.c.o' failed
make[4]: *** [CMakeFiles/websockets.dir/lib/misc/base64-decode.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/websockets.dir/all' failed
make[3]: *** [CMakeFiles/websockets.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make[2]: *** [all] Error 2
/home/uttadmin/esp/IOT/components/libwebsockets/component.mk:20: recipe for target 'build' failed
make[1]: *** [build] Error 2
/home/uttadmin/esp/esp-idf/make/project.mk:493: recipe for target 'component-libwebsockets-build' failed
make: *** [component-libwebsockets-build] Error 2

please help me in this to solve the problem

**Comment by dosgo** [comment]
config.h  define OPENSSL 1

**Comment by ajmalkhanj** [comment]
Thanks for your replay 
I am not able to find  OPENSSL in config.h and i am getting one more error
help in this also 

error: implicit declaration of function 'select' [-Werror=implicit-function-declaration]
     select( 0, NULL, NULL, NULL, &tv );
     ^
cc1: some warnings being treated as errors
/home/uttadmin/esp/esp-idf/make/component_wrapper.mk:285: recipe for target 'port/net_sockets.o' failed
make[1]: *** [port/net_sockets.o] Error 1
/home/uttadmin/esp/esp-idf/make/project.mk:493: recipe for target 'component-mbedtls-build' failed
make: *** [component-mbedtls-build] Error 2

**Comment by dosgo** [comment]
use Makefile.openssl  makefile？

**Comment by ajmalkhanj** [comment]
I am new to this 
i am not getting
Can you please elaborate the steps
I have mentioned one more issue please give solution for that also

error: implicit declaration of function 'select' [-Werror=implicit-function-declaration]
select( 0, NULL, NULL, NULL, &tv );
^
cc1: some warnings being treated as errors
/home/uttadmin/esp/esp-idf/make/component_wrapper.mk:285: recipe for target 'port/net_sockets.o' failed
make[1]: *** [port/net_sockets.o] Error 1
/home/uttadmin/esp/esp-idf/make/project.mk:493: recipe for target 'component-mbedtls-build' failed
make: *** [component-mbedtls-build] Error 2

Thanks
