### ISSUE TITLE
ngrok怎么编译的？

### ISSUE THREAD

**Issue by rxhdiy123** [dosgo/ngrok-c#79]
简书编译方法跟现在版本的对不上，以前试过可以，用Makefle编译出错

**Comment by dosgo** [comment]
看报错更新下就行了吧。。makefile就行了吧。。。然后提交合并 我没使用makefile

**Comment by dosgo** [comment]
用最新的crossbuild.bat编译，基本支持很多平台，不过路由器上我没测试。。应该是可以跑。。
