### ISSUE TITLE
好多memleak。

### ISSUE THREAD

**Issue by wjchen** [dosgo/ngrok-c#8]
Sublime+Sublimelinter有一堆leak提示。
路由器的内存本来就少，不能这么浪费吧。。。

**Comment by dosgo** [comment]
水平有限，只能写到这样了，抱歉。目前在openwrt路由上跑1-2周。。内存也就11%。。不会增加。。

**Comment by wjchen** [comment]
好吧，我fork下

**Comment by wjchen** [comment]
malloc,realloc应该尽量少用， http.cpp里面实在是太多。。。

**Comment by dosgo** [comment]
这个文件没用上

**Comment by wjchen** [comment]
好吧，似乎不支持ngrok2.0, 所以我才来看代码。

**Comment by dosgo** [comment]
不支持2.0？2.0有啥功能？

**Comment by wjchen** [comment]
好像也没啥新功能。。。

**Comment by dosgo** [comment]
我这个根本就没检测版本号。。其实主要协议都没改。。
