### ISSUE TITLE
openwrt环境报错

### ISSUE THREAD

**Issue by fuqiang03** [dosgo/ngrok-c#80]
KERNEL_PATCHVER:=5.10     x86

![捕获](https://user-images.githubusercontent.com/26851715/126215481-38671887-d571-4c39-a0ea-48dee5c0da66.PNG)
![捕获1](https://user-images.githubusercontent.com/26851715/126215492-30015209-8850-42a8-b9b7-a3726f4135c4.PNG)

**Comment by dosgo** [comment]
应该修复了，我好像打错变量名导致了函数指针跟整数对比。你再看下最新的

**Comment by fuqiang03** [comment]
已经通过谢谢修复
![QQ截图20210720122042](https://user-images.githubusercontent.com/26851715/126261413-dcfbd02e-eeae-413e-93fa-3318a6dfae5e.png)
