### ISSUE TITLE
这个客户端是不支持https代理了吗?

### ISSUE THREAD

**Issue by EExuke** [dosgo/ngrok-c#81]
请问是否支持https代理

**Comment by dosgo** [comment]
看服务器的。。。当然如果是自己的域名应该是不支持的。。可以用tcp方式。。不过不能用443端口了

**Comment by EExuke** [comment]
> 看服务器的。。。当然如果是自己的域名应该是不支持的。。可以用tcp方式。。不过不能用443端口了

我这是用的nginx代理的443端口, Emmm...所以是没法用了吗?..........

**Comment by dosgo** [comment]
你本地的端口不重要，什么都可以用，只要你监听了，问题是如果你用自定义域名的话，只能用tcp方式，然后你访问的端口不是443，只能xxx:端口号,如果你用子域名模式看ngrok的服务器是否支持https，如果支持就可以用。。跟你用什么nginx apche没毛线关系

**Comment by EExuke** [comment]
服务器是支持https的,但是客户端这边参数指定为https后,还是会匹配到http,然后本地就会报错说"把http发到了https端口",所以输入参数里type为https有用吗?

**Comment by EExuke** [comment]
你好，问下代理本地443端口为啥不能用了呢？

**Comment by dosgo** [comment]
参数不发出来，日志不发出来，怎么不不可用用法也不发出来，。。你这是占卦呢。。

**Comment by EExuke** [comment]
参数：
 ngrok -SER[Shost:'my_server.com.cn',Sport:4443,Atoken:611246346862400422f6e081,Password:95c3d905-e924-a994-ac34-f73b00614c36] -AddTun[Type:https,Lhost:127.0.0.1,Lport:443,Rport:4443]

 访问获取到的URL，页面显示报错:
     "400 Bad Request"
"The plain HTTP request was sent to HTTPS port"
     "nginx/1.16.1"

另外，如果把 Lhost 换成80就是可以正常访问的， 就443不通。。。你看还需要打印日志不？要我再补。。

**Comment by dosgo** [comment]
你是怎么访问的呢。。

**Comment by dosgo** [comment]
The plain HTTP request was sent to HTTPS port    --->纯 HTTP 请求已发送到 HTTPS 端口

**Comment by EExuke** [comment]
访问就是 直接访问 https://<....获取到的URL域名...>/ 啊。。
方便的话加个QQ(997028792)吧，好沟通些.

**Comment by dosgo** [comment]
加了
