### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by mobiliodevelopment** [dosgo/ngrok-c#84]
Hello there!

I'm trying to run this one but here is what i can see:
```root@orangepizero:~/ngrok-c/build# ./ngrokc -SER[Shost:ngrokd.ngrok.com,Sport:443,Atoken:AUTH_TOKEN] -AddTun[Type:http,Lhost:127.0.0.1,Lport:80]
ngrokc v1.55-(2021/8/30) 
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
update dns
```

I'm pretty sure that AUTH_TOKEN is valid because it's works with official app. But i can't get running any tunnel.

**Comment by mobiliodevelopment** [comment]
Any update on this issue?

**Comment by dosgo** [comment]
I've talked about the service problem, how can I fix it? You can just use the source code of ndrok to build a set.
